import {
  Cake,
  Percent,
  Scale,
  Tag,
  Wallet,
  Receipt,
  Landmark,
  CalendarDays,
  Hourglass,
  Flame,
  AlignLeft,
  Type,
  KeyRound,
  Ruler,
  Weight,
  Thermometer,
  Braces,
  Lock,
  Paperclip,
  Scissors,
  Minimize2,
  DollarSign,
  TrendingUp,
  HandCoins,
  Coins,
  Dices,
  PiggyBank,
  HeartPulse,
  FileText,
  RefreshCw,
  Code2,
  Sparkles,
  CalendarClock,
  ShieldCheck,
  Wrench,
  HelpCircle,
  Briefcase,
  Calculator,
  Layers,
  Fuel,
  BarChart3,
  LineChart,
  HardDrive,
  Link2,
  GraduationCap,
  Target,
  Activity,
  PieChart,
  BadgeDollarSign,
  Droplets,
  Baby,
  Divide,
  Fingerprint,
  FileText as FileTextIcon,
  Home,
  Beaker,
  Gauge,
  Maximize,
  Regex,
  Palette,
  Image,
  FileImage,
  CreditCard,
  Flame as FlameIcon,
  GitCompare,
  ListX,
  Car,
  Scale as ScaleIcon,
  HeartPulse as HeartPulseIcon,
  Sigma,
  Replace,
  Snowflake,
  RadicalIcon,
  RotateCw,
  FileCode,
  Divide as DivideIcon,
  Contrast,
  Palette as PaletteIcon,
  Blend,
  Feather,
  PenTool,
  IdCard,
  MailCheck,
  Stamp,
  Clock,
  CalendarCheck,
  PiggyBank as PiggyBankIcon,
  LineChart as LineChartIcon,
  Umbrella,
  Drumstick,
  Zap,
  CalendarHeart,
  CalendarPlus,
  CalendarMinus,
  Timer,
  CalendarRange,
  Ratio,
  Binary,
  Hash,
  ChartColumn,
  HardHat,
  Blocks,
  Grid2x2,
  PaintBucket,
  LayoutGrid,
  Triangle,
  Mountain,
  Network,
  Waypoints,
  ArrowLeftRight,
  ThermometerSun,
  Apple,
  Square,
  Dice5,
  ChartArea,
  type LucideIcon,
} from "lucide-react";

const TOOL_ICONS: Record<string, LucideIcon> = {
  "age-calculator": Cake,
  "percentage-calculator": Percent,
  "bmi-calculator": Scale,
  "discount-calculator": Tag,
  "emi-calculator": Wallet,
  "gst-calculator": Receipt,
  "loan-calculator": Landmark,
  "date-calculator": CalendarDays,
  "countdown-timer": Hourglass,
  "bmr-calculator": Flame,
  "word-counter": AlignLeft,
  "case-converter": Type,
  "password-generator": KeyRound,
  "length-converter": Ruler,
  "weight-converter": Weight,
  "temperature-converter": Thermometer,
  "json-formatter": Braces,
  "base64-tool": Lock,
  "merge-pdf": Paperclip,
  "split-pdf": Scissors,
  "compress-pdf": Minimize2,
  "currency-converter": DollarSign,
  "compound-interest-calculator": TrendingUp,
  "tip-calculator": HandCoins,
  "simple-interest-calculator": Coins,
  "random-number-generator": Dices,
  "salary-calculator": Briefcase,
  "sales-tax-calculator": Calculator,
  "fuel-cost-calculator": Fuel,
  "discount-stack-calculator": Layers,
  "extra-payment-calculator": Landmark,
  "text-summarizer": Sparkles,
  "paragraph-rewriter": Sparkles,
  "roi-calculator": BarChart3,
  "markup-calculator": LineChart,
  "data-storage-converter": HardDrive,
  "url-encoder": Link2,
  "gpa-calculator": GraduationCap,
  "ideal-weight-calculator": Target,
  "body-fat-calculator": Activity,
  "inflation-calculator": PieChart,
  "net-worth-calculator": BadgeDollarSign,
  "water-intake-calculator": Droplets,
  "pregnancy-due-date-calculator": Baby,
  "fraction-calculator": Divide,
  "uuid-generator": Fingerprint,
  "lorem-ipsum-generator": FileTextIcon,
  "mortgage-calculator": Home,
  "volume-converter": Beaker,
  "speed-converter": Gauge,
  "area-converter": Maximize,
  "regex-tester": Regex,
  "hex-rgb-converter": Palette,
  "pdf-to-jpg": Image,
  "jpg-to-pdf": FileImage,
  "credit-card-payoff-calculator": CreditCard,
  "calorie-goal-calculator": FlameIcon,
  "text-diff-checker": GitCompare,
  "remove-duplicate-lines": ListX,
  "auto-loan-calculator": Car,
  "breakeven-calculator": ScaleIcon,
  "heart-rate-zone-calculator": HeartPulseIcon,
  "standard-deviation-calculator": Sigma,
  "find-and-replace": Replace,
  "debt-payoff-calculator": Snowflake,
  "quadratic-solver": RadicalIcon,
  "rotate-pdf": RotateCw,
  "markdown-previewer": FileCode,
  "scientific-calculator": DivideIcon,
  "contrast-checker": Contrast,
  "color-palette-generator": PaletteIcon,
  "hsl-converter": Blend,
  "font-signature-generator": Feather,
  "handwritten-signature-pad": PenTool,
  "email-signature-generator": IdCard,
  "email-format-validator": MailCheck,
  "watermark-pdf": Stamp,
  "timezone-converter": Clock,
  "working-days-calculator": CalendarCheck,
  "savings-goal-calculator": PiggyBankIcon,
  "sip-calculator": LineChartIcon,
  "retirement-calculator": Umbrella,
  "protein-calculator": Drumstick,
  "tdee-calculator": Zap,
  "ovulation-calculator": CalendarHeart,
  "add-days-calculator": CalendarPlus,
  "subtract-days-calculator": CalendarMinus,
  "time-duration-calculator": Timer,
  "week-number-calculator": CalendarRange,
  "ratio-calculator": Ratio,
  "lcm-calculator": Binary,
  "prime-number-calculator": Hash,
  "mean-median-mode-calculator": ChartColumn,
  "concrete-calculator": Blocks,
  "tile-calculator": Grid2x2,
  "paint-calculator": PaintBucket,
  "flooring-calculator": LayoutGrid,
  "roofing-calculator": Triangle,
  "gravel-calculator": Mountain,
  "subnet-calculator": Network,
  "cidr-range-calculator": Waypoints,
  "ip-address-converter": ArrowLeftRight,
  "btu-calculator": ThermometerSun,
  "macro-calculator": Apple,
  "square-footage-calculator": Square,
  "probability-calculator": Dice5,
  "statistics-calculator": ChartArea,
};

const CATEGORY_ICONS: Record<string, LucideIcon> = {
  finance: PiggyBank,
  health: HeartPulse,
  pdf: FileText,
  converters: RefreshCw,
  developer: Code2,
  text: Type,
  ai: Sparkles,
  "date-time": CalendarClock,
  security: ShieldCheck,
  misc: Wrench,
  math: Calculator,
  construction: HardHat,
};

export function getToolIcon(slug: string): LucideIcon {
  return TOOL_ICONS[slug] ?? HelpCircle;
}

export function getCategoryIcon(slug: string): LucideIcon {
  return CATEGORY_ICONS[slug] ?? Wrench;
}