import {
  Cake,
  Percent,
  Scale,
  Tag,
  Wallet,
  Receipt,
  Landmark,
  CalendarDays,
  Hourglass,
  Flame,
  AlignLeft,
  Type,
  KeyRound,
  Ruler,
  Weight,
  Thermometer,
  Braces,
  Lock,
  Paperclip,
  Scissors,
  Minimize2,
  DollarSign,
  TrendingUp,
  HandCoins,
  Coins,
  Dices,
  PiggyBank,
  HeartPulse,
  FileText,
  RefreshCw,
  Code2,
  Sparkles,
  CalendarClock,
  ShieldCheck,
  Wrench,
  HelpCircle,
  type LucideIcon,
} from "lucide-react";

const TOOL_ICONS: Record<string, LucideIcon> = {
  "age-calculator": Cake,
  "percentage-calculator": Percent,
  "bmi-calculator": Scale,
  "discount-calculator": Tag,
  "emi-calculator": Wallet,
  "gst-calculator": Receipt,
  "loan-calculator": Landmark,
  "date-calculator": CalendarDays,
  "countdown-timer": Hourglass,
  "bmr-calculator": Flame,
  "word-counter": AlignLeft,
  "case-converter": Type,
  "password-generator": KeyRound,
  "length-converter": Ruler,
  "weight-converter": Weight,
  "temperature-converter": Thermometer,
  "json-formatter": Braces,
  "base64-tool": Lock,
  "merge-pdf": Paperclip,
  "split-pdf": Scissors,
  "compress-pdf": Minimize2,
  "currency-converter": DollarSign,
  "compound-interest-calculator": TrendingUp,
  "tip-calculator": HandCoins,
  "simple-interest-calculator": Coins,
  "random-number-generator": Dices,
};

const CATEGORY_ICONS: Record<string, LucideIcon> = {
  finance: PiggyBank,
  health: HeartPulse,
  pdf: FileText,
  converters: RefreshCw,
  developer: Code2,
  text: Type,
  ai: Sparkles,
  "date-time": CalendarClock,
  security: ShieldCheck,
  misc: Wrench,
};

export function getToolIcon(slug: string): LucideIcon {
  return TOOL_ICONS[slug] ?? HelpCircle;
}

export function getCategoryIcon(slug: string): LucideIcon {
  return CATEGORY_ICONS[slug] ?? Wrench;
}